<?php
  $lang['number']		= 'Referenz';
  $lang['date']			= 'Rechnungsdatum';
  $lang['due']			= 'Fälligkeitsdatum';
  $lang['to']			= 'Abrechnung';
  $lang['from']			= 'Unseren Informationen ';
  $lang['product']		= 'Produkt';
  $lang['qty']			= 'Menge';
  $lang['price']		= 'Preis';
  $lang['discount']		= 'Rabatt';
  $lang['vat']			= 'Steuer';
  $lang['total']		= 'Gesamt';
  $lang['page']			= 'Seite';
  $lang['page_of']		= 'von';
  $lang['isbn'] = 'ISBN';
  $lang['editor'] = 'Editore';
  $lang['author'] = 'Autore';
  $lang['description'] = 'Descrizione';
  $lang['qty']			= 'Q.tà';
  $lang['price']		= 'Prezzo';
  $lang['total']		= 'Importo';
?>