<?php
  $lang['number']		= 'Referencia';
  $lang['date']			= 'Fecha';
  $lang['due']			= 'Facha de vencimiento';
  $lang['to']			= 'Facturación a';
  $lang['from']			= 'Nuestra información ';
  $lang['product']		= 'Producto';
  $lang['qty']			= 'Cantidad';
  $lang['price']		= 'Precio';
  $lang['discount']		= 'Descuento';
  $lang['vat']			= 'Impuestos';
  $lang['total']		= 'Total de';
  $lang['page']			= 'Página';
  $lang['page_of']		= 'de';
  $lang['isbn'] = 'ISBN';
  $lang['editor'] = 'Editore';
  $lang['author'] = 'Autore';
  $lang['description'] = 'Descrizione';
  $lang['qty']			= 'Q.tà';
  $lang['price']		= 'Prezzo';
  $lang['total']		= 'Importo';
?>