<?php
  $lang['number']		= 'Riferimento';
  $lang['date']			= 'Data di fatturazione';
  $lang['time']			= 'Ora di fatturazione';
  $lang['due']			= 'Scadenza';
  $lang['to']			= 'Per accettazione';
  $lang['from']			= 'Cliente';
  $lang['product']		= 'Prodotto';
  $lang['isbn'] = 'ISBN';
  $lang['editor'] = 'Editore';
  $lang['author'] = 'Autore';
  $lang['description'] = 'Descrizione';
  $lang['qty']			= 'Q.tà';
  $lang['price']		= 'Prezzo';
  $lang['discount']		= 'Sconto';
  $lang['vat']			= 'Imposta';
  $lang['total']		= 'Importo';
  $lang['page']			= 'Pagina';
  $lang['page_of']		= 'di';
?>